//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sbc11WcfClient.Common.OsterFabrikService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Produkt", Namespace="http://schemas.datacontract.org/2004/07/Sbc11WorkflowService.Communication")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Sbc11WcfClient.Common.OsterFabrikService.SchokoHase))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Sbc11WcfClient.Common.OsterFabrikService.Nest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Sbc11WcfClient.Common.OsterFabrikService.Ei))]
    public partial class Produkt : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProduzentField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Produzent {
            get {
                return this.ProduzentField;
            }
            set {
                if ((object.ReferenceEquals(this.ProduzentField, value) != true)) {
                    this.ProduzentField = value;
                    this.RaisePropertyChanged("Produzent");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SchokoHase", Namespace="http://schemas.datacontract.org/2004/07/Sbc11WorkflowService.Communication")]
    [System.SerializableAttribute()]
    public partial class SchokoHase : Sbc11WcfClient.Common.OsterFabrikService.Produkt {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Nest", Namespace="http://schemas.datacontract.org/2004/07/Sbc11WorkflowService.Communication")]
    [System.SerializableAttribute()]
    public partial class Nest : Sbc11WcfClient.Common.OsterFabrikService.Produkt {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Sbc11WcfClient.Common.OsterFabrikService.Ei[] EierField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Sbc11WcfClient.Common.OsterFabrikService.SchokoHase SchokoHaseField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Sbc11WcfClient.Common.OsterFabrikService.Ei[] Eier {
            get {
                return this.EierField;
            }
            set {
                if ((object.ReferenceEquals(this.EierField, value) != true)) {
                    this.EierField = value;
                    this.RaisePropertyChanged("Eier");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Sbc11WcfClient.Common.OsterFabrikService.SchokoHase SchokoHase {
            get {
                return this.SchokoHaseField;
            }
            set {
                if ((object.ReferenceEquals(this.SchokoHaseField, value) != true)) {
                    this.SchokoHaseField = value;
                    this.RaisePropertyChanged("SchokoHase");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Ei", Namespace="http://schemas.datacontract.org/2004/07/Sbc11WorkflowService.Communication")]
    [System.SerializableAttribute()]
    public partial class Ei : Sbc11WcfClient.Common.OsterFabrikService.Produkt {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FarbeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MalerField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Farbe {
            get {
                return this.FarbeField;
            }
            set {
                if ((object.ReferenceEquals(this.FarbeField, value) != true)) {
                    this.FarbeField = value;
                    this.RaisePropertyChanged("Farbe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Maler {
            get {
                return this.MalerField;
            }
            set {
                if ((object.ReferenceEquals(this.MalerField, value) != true)) {
                    this.MalerField = value;
                    this.RaisePropertyChanged("Maler");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="OsterFabrikService.IOsterFabrikService", CallbackContract=typeof(Sbc11WcfClient.Common.OsterFabrikService.IOsterFabrikServiceCallback))]
    public interface IOsterFabrikService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOsterFabrikService/AddUnbemaltesEi", ReplyAction="http://tempuri.org/IOsterFabrikService/AddUnbemaltesEiResponse")]
        void AddUnbemaltesEi(Sbc11WcfClient.Common.OsterFabrikService.Ei ei);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOsterFabrikService/AddBemaltesEi", ReplyAction="http://tempuri.org/IOsterFabrikService/AddBemaltesEiResponse")]
        void AddBemaltesEi(Sbc11WcfClient.Common.OsterFabrikService.Ei ei);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOsterFabrikService/AddSchokoHase", ReplyAction="http://tempuri.org/IOsterFabrikService/AddSchokoHaseResponse")]
        void AddSchokoHase(Sbc11WcfClient.Common.OsterFabrikService.SchokoHase schokoHase);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOsterFabrikService/AddNest", ReplyAction="http://tempuri.org/IOsterFabrikService/AddNestResponse")]
        void AddNest(Sbc11WcfClient.Common.OsterFabrikService.Nest nest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOsterFabrikService/LookForUnbemaltesEi", ReplyAction="http://tempuri.org/IOsterFabrikService/LookForUnbemaltesEiResponse")]
        void LookForUnbemaltesEi();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOsterFabrikService/LookForBemaltesEi", ReplyAction="http://tempuri.org/IOsterFabrikService/LookForBemaltesEiResponse")]
        void LookForBemaltesEi();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOsterFabrikService/LookForSchokoHase", ReplyAction="http://tempuri.org/IOsterFabrikService/LookForSchokoHaseResponse")]
        void LookForSchokoHase();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOsterFabrikService/LookForNest", ReplyAction="http://tempuri.org/IOsterFabrikService/LookForNestResponse")]
        void LookForNest();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOsterFabrikService/NotifyNestVerschickt", ReplyAction="http://tempuri.org/IOsterFabrikService/NotifyNestVerschicktResponse")]
        void NotifyNestVerschickt(Sbc11WcfClient.Common.OsterFabrikService.Nest nest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOsterFabrikService/RegisterForUnbemalteEierNotifications", ReplyAction="http://tempuri.org/IOsterFabrikService/RegisterForUnbemalteEierNotificationsRespo" +
            "nse")]
        void RegisterForUnbemalteEierNotifications();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOsterFabrikService/RegisterForBemalteEierNotifications", ReplyAction="http://tempuri.org/IOsterFabrikService/RegisterForBemalteEierNotificationsRespons" +
            "e")]
        void RegisterForBemalteEierNotifications();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOsterFabrikService/RegisterForSchokoHasenNotifications", ReplyAction="http://tempuri.org/IOsterFabrikService/RegisterForSchokoHasenNotificationsRespons" +
            "e")]
        void RegisterForSchokoHasenNotifications();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOsterFabrikService/RegisterForNesterNotifications", ReplyAction="http://tempuri.org/IOsterFabrikService/RegisterForNesterNotificationsResponse")]
        void RegisterForNesterNotifications();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOsterFabrikService/RegisterForLogistikNotifications", ReplyAction="http://tempuri.org/IOsterFabrikService/RegisterForLogistikNotificationsResponse")]
        void RegisterForLogistikNotifications();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOsterFabrikService/UnRegisterFromUnbemalteEierNotifications", ReplyAction="http://tempuri.org/IOsterFabrikService/UnRegisterFromUnbemalteEierNotificationsRe" +
            "sponse")]
        void UnRegisterFromUnbemalteEierNotifications();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOsterFabrikService/UnRegisterFromBemalteEierNotifications", ReplyAction="http://tempuri.org/IOsterFabrikService/UnRegisterFromBemalteEierNotificationsResp" +
            "onse")]
        void UnRegisterFromBemalteEierNotifications();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOsterFabrikService/UnRegisterFromSchokoHasenNotifications", ReplyAction="http://tempuri.org/IOsterFabrikService/UnRegisterFromSchokoHasenNotificationsResp" +
            "onse")]
        void UnRegisterFromSchokoHasenNotifications();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOsterFabrikService/UnRegisterFromNesterNotifications", ReplyAction="http://tempuri.org/IOsterFabrikService/UnRegisterFromNesterNotificationsResponse")]
        void UnRegisterFromNesterNotifications();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOsterFabrikService/UnRegisterFromLogistikNotifications", ReplyAction="http://tempuri.org/IOsterFabrikService/UnRegisterFromLogistikNotificationsRespons" +
            "e")]
        void UnRegisterFromLogistikNotifications();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOsterFabrikServiceCallback {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOsterFabrikService/NotifyUnbemaltesEiChanged", ReplyAction="http://tempuri.org/IOsterFabrikService/NotifyUnbemaltesEiChangedResponse")]
        void NotifyUnbemaltesEiChanged(int currentCount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOsterFabrikService/NotifyBemaltesEiChanged", ReplyAction="http://tempuri.org/IOsterFabrikService/NotifyBemaltesEiChangedResponse")]
        void NotifyBemaltesEiChanged(int currentCount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOsterFabrikService/NotifySchokoHaseChanged", ReplyAction="http://tempuri.org/IOsterFabrikService/NotifySchokoHaseChangedResponse")]
        void NotifySchokoHaseChanged(int currentCount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOsterFabrikService/NotifyNestChanged", ReplyAction="http://tempuri.org/IOsterFabrikService/NotifyNestChangedResponse")]
        void NotifyNestChanged(int currentcount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOsterFabrikService/NotifyLogistikChanged", ReplyAction="http://tempuri.org/IOsterFabrikService/NotifyLogistikChangedResponse")]
        void NotifyLogistikChanged(int currentlyDelivered);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOsterFabrikService/ReturnUnbemaltesEi", ReplyAction="http://tempuri.org/IOsterFabrikService/ReturnUnbemaltesEiResponse")]
        void ReturnUnbemaltesEi(Sbc11WcfClient.Common.OsterFabrikService.Ei ei);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOsterFabrikService/ReturnBemaltesEi", ReplyAction="http://tempuri.org/IOsterFabrikService/ReturnBemaltesEiResponse")]
        void ReturnBemaltesEi(Sbc11WcfClient.Common.OsterFabrikService.Ei ei);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOsterFabrikService/ReturnSchokoHase", ReplyAction="http://tempuri.org/IOsterFabrikService/ReturnSchokoHaseResponse")]
        void ReturnSchokoHase(Sbc11WcfClient.Common.OsterFabrikService.SchokoHase hase);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOsterFabrikService/ReturnNest", ReplyAction="http://tempuri.org/IOsterFabrikService/ReturnNestResponse")]
        void ReturnNest(Sbc11WcfClient.Common.OsterFabrikService.Nest nest);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOsterFabrikServiceChannel : Sbc11WcfClient.Common.OsterFabrikService.IOsterFabrikService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OsterFabrikServiceClient : System.ServiceModel.DuplexClientBase<Sbc11WcfClient.Common.OsterFabrikService.IOsterFabrikService>, Sbc11WcfClient.Common.OsterFabrikService.IOsterFabrikService {
        
        public OsterFabrikServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public OsterFabrikServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public OsterFabrikServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public OsterFabrikServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public OsterFabrikServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void AddUnbemaltesEi(Sbc11WcfClient.Common.OsterFabrikService.Ei ei) {
            base.Channel.AddUnbemaltesEi(ei);
        }
        
        public void AddBemaltesEi(Sbc11WcfClient.Common.OsterFabrikService.Ei ei) {
            base.Channel.AddBemaltesEi(ei);
        }
        
        public void AddSchokoHase(Sbc11WcfClient.Common.OsterFabrikService.SchokoHase schokoHase) {
            base.Channel.AddSchokoHase(schokoHase);
        }
        
        public void AddNest(Sbc11WcfClient.Common.OsterFabrikService.Nest nest) {
            base.Channel.AddNest(nest);
        }
        
        public void LookForUnbemaltesEi() {
            base.Channel.LookForUnbemaltesEi();
        }
        
        public void LookForBemaltesEi() {
            base.Channel.LookForBemaltesEi();
        }
        
        public void LookForSchokoHase() {
            base.Channel.LookForSchokoHase();
        }
        
        public void LookForNest() {
            base.Channel.LookForNest();
        }
        
        public void NotifyNestVerschickt(Sbc11WcfClient.Common.OsterFabrikService.Nest nest) {
            base.Channel.NotifyNestVerschickt(nest);
        }
        
        public void RegisterForUnbemalteEierNotifications() {
            base.Channel.RegisterForUnbemalteEierNotifications();
        }
        
        public void RegisterForBemalteEierNotifications() {
            base.Channel.RegisterForBemalteEierNotifications();
        }
        
        public void RegisterForSchokoHasenNotifications() {
            base.Channel.RegisterForSchokoHasenNotifications();
        }
        
        public void RegisterForNesterNotifications() {
            base.Channel.RegisterForNesterNotifications();
        }
        
        public void RegisterForLogistikNotifications() {
            base.Channel.RegisterForLogistikNotifications();
        }
        
        public void UnRegisterFromUnbemalteEierNotifications() {
            base.Channel.UnRegisterFromUnbemalteEierNotifications();
        }
        
        public void UnRegisterFromBemalteEierNotifications() {
            base.Channel.UnRegisterFromBemalteEierNotifications();
        }
        
        public void UnRegisterFromSchokoHasenNotifications() {
            base.Channel.UnRegisterFromSchokoHasenNotifications();
        }
        
        public void UnRegisterFromNesterNotifications() {
            base.Channel.UnRegisterFromNesterNotifications();
        }
        
        public void UnRegisterFromLogistikNotifications() {
            base.Channel.UnRegisterFromLogistikNotifications();
        }
    }
}
